#A make file example : instructions on how to dress
#Using the automatic variable $@
#$@ is the name of the target

coat : shoes mobile sweater
	@echo Put on $@
#here $@ means the coat
	
shoes : socks trousers
	@echo Put on $@
	
mobile : trousers
	@echo Put on $@

sweater : shirt
	@echo Put on $@

trousers : underpants shirt
	@echo Put on $@
	
shirt : undershirt
	@echo Put on $@
	
socks : 
	@echo Put on $@

underpants : 
	@echo Put on $@
	
undershirt : 
	@echo Put on $@
		