#A make file example : instructions on how to dress


coat : shoes mobile sweater
	@echo Put on coat
#coat is called target
#shoes mobile sweater are called prerequisites
#@echo "Put on coat" is called the command
#The whole thing is knows as a rule


shoes : socks trousers
	@echo Put on shoes
	
mobile : trousers
	@echo Put on mobile

sweater : shirt
	@echo Put on sweater

trousers : underpants shirt
	@echo Put on trousers
	
shirt : undershirt
	@echo Put on shirt
	
socks : 
	@echo Put on socks

underpants : 
	@echo Put on underpants
	
undershirt : 
	@echo Put on undershirt
		